FROM ubuntu
RUN apt update && apt install -yq --no-install-recommends \
    apache2 \
    nano \
    curl \
    net-tools iputils-ping

WORKDIR /usr/local/apache2/htdocs
COPY ../src .
EXPOSE 80
CMD apachectl -DFOREGROUND