#Imagen base de apache con ubuntu actualizado
FROM ubuntu
ARG USUARIO
#Instalacion de paquetes ejje
RUN apt update && apt install -yq --no-install-recommends \
    nano \
    curl \
    net-tools iputils-ping
#Creacion de usuario 
RUN useradd -rm -d /home/jiahaolinwu -s /bin/bash ${USUARIO}
RUN echo "${USUARIO}:jiahaolinwu" | chpasswd
RUN echo "Bienvenido ${USUARIO} a la empresa" > /home/${USUARIO}/hola.txt

CMD ["tail", "-f", "/dev/null"]