FROM ubuntu
ARG USUARIO
ARG PASSWORD
RUN apt update && apt install -y --no-install-recommends \
    nano \
    git curl wget \
    iputils-ping  net-tools\
    sudo 
    
RUN useradd -rm -d /home/jiahaolinwu -s /bin/bash ${USUARIO}
RUN echo "${USUARIO}:jiahaolinwu" | chpasswd
RUN echo "Bienvenido ${USUARIO} a la empresa" > /home/${USUARIO}/hola.txt

